# SPDX-License-Identifier: MIT
"""Pyrolysis gas mass flux accumulation.

The gas generated by decomposition in any cell travels toward the surface.
The cumulative mass flux at node n is the sum of all gas generated in cells
from n to the back of the layer:

    m_dot_g(n) [kg/s] = -sum_{k=n}^{N_ablating} A_k * (drho/dt|_y)_k * delta_k

Dividing by A_n gives the mass flux density [kg/m^2/s] at node n's position.

The total pyrolysis gas reaching the surface is m_dot_g(0) / A_surface.
"""

from __future__ import annotations

import numpy as np
from numpy.typing import NDArray


def pyrolysis_gas_flow_rate(
    drho_dt_y: NDArray,    # [kg/m^3/s] per node (negative = losing mass)
    delta_nodes: NDArray,  # [m] cell thicknesses
    area_nodes: NDArray,   # [m^2] cell areas
    layer_bounds: tuple,   # (first_global_idx, last_global_idx+1) for the ablating layer
) -> NDArray:
    """Compute cumulative pyrolysis gas mass flow rate at each node [kg/s].

    Parameters
    ----------
    drho_dt_y:
        Decomposition rate (at fixed y) per node [kg/m^3/s], shape (N_total,).
        Negative for mass generation (material decomposing).
    delta_nodes:
        Cell thicknesses [m], shape (N_total,).
    area_nodes:
        Cell areas [m^2], shape (N_total,).
    layer_bounds:
        (lo, hi) index range for the ablating layer.

    Returns
    -------
    m_dot_g_nodes: NDArray
        Mass flow rate [kg/s] at each global node, shape (N_total,).
        Non-zero only within the ablating layer.
        m_dot_g_nodes[0] / area_nodes[0] = surface mass flux [kg/m^2/s].
    """
    lo, hi = layer_bounds
    N_total = len(drho_dt_y)
    m_dot_g = np.zeros(N_total)

    # Accumulate from back to front.  Gas from cell k contributes
    # -drho_dt * A * delta to all cells k and shallower.
    generation = -drho_dt_y[lo:hi] * area_nodes[lo:hi] * delta_nodes[lo:hi]
    m_dot_g[lo:hi] = np.cumsum(generation[::-1])[::-1]

    return m_dot_g


def surface_pyrolysis_flux(
    drho_dt_y: NDArray,
    delta_nodes: NDArray,
    area_nodes: NDArray,
    layer_bounds: tuple,
) -> float:
    """Total pyrolysis gas mass flux at the surface [kg/m^2/s].

    Equal to m_dot_g(0) / A_surface.
    """
    m_dot_g = pyrolysis_gas_flow_rate(drho_dt_y, delta_nodes, area_nodes, layer_bounds)
    lo = layer_bounds[0]
    A_surface = area_nodes[lo]
    if A_surface <= 0:
        return 0.0
    return m_dot_g[lo] / A_surface
